"""
this file contains payload models used for getting desired response
"""
# generated by datamodel-codegen:
#   filename:  response_json.json
#   timestamp: 2024-01-22T11:42:05+00:00

from pydantic import BaseModel

class User(BaseModel):
    firstName: str = "Muhammad"
    lastName: str = "Ovi"
    age: int = 45  