"""
this file contains Schema models to validate the received response
"""

# generated by datamodel-codegen:
#   filename:  response_json.json
#   timestamp: 2024-01-22T10:41:03+00:00

from typing import List
from pydantic import BaseModel

class Message(BaseModel):
    id: int
    firstName: str
    lastName: str
    age: int

class Todo(BaseModel):
    id: int
    todo: str
    completed: bool
    userId: int

class UserTodos(BaseModel):
    todos: List[Todo]
    total: int
    skip: int
    limit: int    
